# MASTER STABILITY SETTINGS
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true

# Critical fix for OneDrive "Failed to create Jar" and "bcprov" errors
org.gradle.vfs.watch=false
org.gradle.caching=false
org.gradle.parallel=false

# Fix for Red Lines in IDE
android.nonTransitiveRClass=true
android.nonFinalResIds=false
