services:
  - type: web
    name: ss-elearning-api
    env: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: ss_elearning_jwt_secret_2024
      - key: GMAIL_USER
        value: thiyangkoang77@gmail.com
      - key: GMAIL_APP_PASSWORD
        value: REPLACE_WITH_GMAIL_APP_PASSWORD
      - key: MONGO_URI
        value: REPLACE_WITH_MONGO_URI
      - key: CLIENT_URL
        value: https://south-sudanese-learning-app-two.vercel.app
